# This workflow tests the code in a production-like environment on our internal dev machine.
name: CI/CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Package
      run: |
        make build

  deploy:
    # TODO: This should be on merge to main not on pull request creation
    if: github.event_name == 'pull_request'
    needs: build
    concurrency: deploy

    steps:
      - name: Post to Splunk SOAR API
        run: |
          make deploy
