name: Detect Secrets

on: pull_request

jobs:
  detect-secrets:
    runs-on: ubuntu-22.04
    container: python:latest

    steps:
    - uses: actions/checkout@v3

    - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - name: Install Yelp's detect secrets
      run: |
        apt-get update && apt-get install -y jq
        pip install yq
        pip install detect-secrets==$(yq -r .repos[0].rev .pre-commit-config.yaml)

    - name: Detect potential secrets
      run: git ls-files -z | xargs -0 detect-secrets-hook --baseline .secrets.baseline
